CREATE DATABASE whatTheText;

USE whatTheText;

CREATE TABLE `user_tbl` (
	id INT AUTO_INCREMENT NOT NULL
	,`username` VARCHAR(30) NOT NULL
	,`password`	VARCHAR(30) NOT NULL
	,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,`updated_at` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (id)
);

CREATE TABLE `text_tbl` (
	`id` INT AUTO_INCREMENT NOT NULL
	,`image` BLOB NOT NULL
	,`caption` VARCHAR(255) NOT NULL
	,`ew` BOOL DEFAULT 0
	,`bff` BOOL DEFAULT 0
	,`lol` BOOL DEFAULT 0
	,`nsfw` BOOL DEFAULT 0
	,`fail` BOOL DEFAULT 0
	,`wtfam` BOOL DEFAULT 0
	,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,`updated_at` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (`id`)
	,FOREIGN KEY (`ownerId`) REFERENCES `user_tbl` (`id`)
);

CREATE TABLE `comment_tbl` (
	`id` INT AUTO_INCREMENT NOT NULL
	,`comment` VARCHAR(255) NOT NULL
	,`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	,`updated_at` TIMESTAMP DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (`id`)
	,FOREIGN KEY (`commentorId`) REFERENCES `user_tbl` (`id`)
);

CREATE TABLE `reaction_tbl` (
	`id` INT AUTO_INCREMENT NOT NULL
	`like` BOOL NOT NULL
	,PRIMARY KEY (`id`)
	,FOREIGN KEY (`voter_id`) REFERENCES `user_tbl` (`id`)
	,FOREIGN KEY (`text_id`) REFERENCES `text_tbl` (`id`)
);